// build.rs — copies the schema file into OUT_DIR so that schema.rs can embed
// it with `include_bytes!(concat!(env!("OUT_DIR"), "/schema.toml"))`.
//
// Schema source resolution (first match wins):
//   1. SETTINGS_SCHEMA env var — absolute path or relative to the workspace root
//   2. {CARGO_MANIFEST_DIR}/demo/schema.toml  (default for standalone dev)

use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());

    let schema_src = std::env::var("SETTINGS_SCHEMA")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("demo/schema.toml"));

    settings_schema::check_schema_file(&schema_src).unwrap_or_else(|msg| {
        panic!("{msg}");
    });

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let schema_dest = out_dir.join("schema.toml");

    std::fs::copy(&schema_src, &schema_dest).unwrap_or_else(|e| {
        panic!(
            "Failed to copy schema from '{}': {e}\n\
             Set SETTINGS_SCHEMA=/path/to/schema.toml to override.",
            schema_src.display()
        )
    });

    // Re-run the build script when the schema or the env var changes.
    println!("cargo:rerun-if-changed={}", schema_src.display());
    println!("cargo:rerun-if-env-changed=SETTINGS_SCHEMA");

    // Optional icon assets — present only when `make icons` was run.
    // When found, copy them to OUT_DIR and set the `has_icons` cfg flag so
    // the icon font is embedded and icon tab rendering is compiled in.
    let assets_dir = manifest_dir.join("assets");
    let icon_ttf_src = assets_dir.join("icons.ttf");
    let icon_cp_src = assets_dir.join("icons.codepoints");
    // Declare the custom cfg key so rustc does not warn about it in source files.
    println!("cargo::rustc-check-cfg=cfg(has_icons)");
    if icon_ttf_src.exists() && icon_cp_src.exists() {
        std::fs::copy(&icon_ttf_src, out_dir.join("icons.ttf"))
            .expect("build.rs: failed to copy assets/icons.ttf to OUT_DIR");
        std::fs::copy(&icon_cp_src, out_dir.join("icons.codepoints"))
            .expect("build.rs: failed to copy assets/icons.codepoints to OUT_DIR");
        println!("cargo:rustc-cfg=has_icons");
    } else {
        println!("cargo:warning=Icon assets not found in 'assets/'. Run `make icons` to enable icon support.");
    }
    println!("cargo:rerun-if-changed={}", icon_ttf_src.display());
    println!("cargo:rerun-if-changed={}", icon_cp_src.display());

    // Embed icon into the Windows .exe so Explorer shows a file icon.
    // The .ico is generated by `make win` (via the $(APPICON_ICO) file rule)
    // before cargo build runs, so it is always present when building for Windows.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        let ico = assets_dir.join("appicon.ico");
        println!("cargo:rerun-if-changed={}", ico.display());
        if ico.exists() {
            let mut res = winresource::WindowsResource::new();
            res.set_icon(ico.to_str().unwrap());
            res.compile()
                .expect("build.rs: failed to compile Windows icon resource");
        } else {
            println!(
                "cargo:warning=assets/appicon.ico not found — \
                 .exe will have no file icon. Run `make win` to generate it."
            );
        }
    }
}
