# ============================================================
# Settings — production build targets
# ============================================================
# Usage:
#   make               — release binary (macOS/Linux, current arch)
#   make win           — Windows .exe (cross-compiled from macOS via mingw-w64)
#   make win-zip       — zip the Windows .exe for distribution
#   make icons         — download Material Symbols icon font
#   make SCHEMA=/path/to/schema.toml [binary|win]  — custom schema
#   make ICON_STYLE=outlined icons  — override icon variant
#
# For standalone demo builds (macOS .app, notarize, Linux binary, etc.),
# see demo/Makefile.
#
# Windows cross-compile prerequisites (run once on the build host):
#   brew install mingw-w64
#   rustup target add x86_64-pc-windows-gnu
#
# Outputs:
#   target/release/settings            — binary for bundling into the parent app
#   dist/settings-windows/Settings.exe — Windows executable (distributed standalone)
# ============================================================

APP_NAME  := Settings
EXE_NAME  := settings
VERSION   := $(shell awk -F'"' '/^version *=/{print $$2; exit}' Cargo.toml)

# Schema file to embed.
# Default: ../schema.toml (relative to this Makefile).
# Override: make SCHEMA=/absolute/path/to/schema.toml
SCHEMA ?= ../schema.toml

DIST        := dist
RELEASE_BIN := target/release/$(EXE_NAME)

# App icon for Windows PE resource (generated by the $(APPICON_ICO) file rule).
APPICON_ICO := assets/appicon.ico

# Windows cross-compile target.
# A space-free CARGO_TARGET_DIR is used to work around a dlltool limitation
# (mingw-w64 dlltool fails on paths containing spaces).
WIN_TARGET     := x86_64-pc-windows-gnu
WIN_TARGET_DIR := /tmp/settings-win
WIN_DIR        := $(DIST)/settings-windows
WIN_EXE        := $(WIN_DIR)/$(APP_NAME).exe
WIN_ZIP        := $(DIST)/$(APP_NAME)-v$(VERSION)-windows-x86_64.zip

# ── helpers ─────────────────────────────────────────────────
# Resolve SCHEMA to an absolute path so build.rs receives it correctly
# regardless of the working directory.
ABS_SCHEMA := $(abspath $(SCHEMA))

# ── icon font ───────────────────────────────────────────────
# Icon style: read from schema.toml, override with ICON_STYLE=... on the
# command line (e.g. `make icons ICON_STYLE=outlined`).
ICON_STYLE ?= $(or $(shell awk -F'"' '/^icon_style/{print $$2}' "$(SCHEMA)" 2>/dev/null | head -1),rounded)

ifeq ($(ICON_STYLE),outlined)
  ICON_VARIANT := Outlined
else ifeq ($(ICON_STYLE),sharp)
  ICON_VARIANT := Sharp
else
  ICON_VARIANT := Rounded
endif

ASSETS_DIR    := assets
ICON_TTF      := $(ASSETS_DIR)/icons.ttf
ICON_CP       := $(ASSETS_DIR)/icons.codepoints
ICON_URL_BASE := https://raw.githubusercontent.com/google/material-design-icons/master/variablefont
ICON_TTF_FILE := MaterialSymbols$(ICON_VARIANT)%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf
ICON_CP_FILE  := MaterialSymbols$(ICON_VARIANT)%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints

# ── targets ─────────────────────────────────────────────────

.PHONY: all binary schema-check win win-zip icons appicon-ico clean help

## Default: build the release binary (current arch).
all: binary

# File rule: download both icon assets when they are missing.
# `binary` depends on this, so icons are fetched automatically on first build.
$(ICON_TTF):
	@mkdir -p $(ASSETS_DIR)
	@echo ">>> Downloading Material Symbols $(ICON_VARIANT)  (style: $(ICON_STYLE))"
	curl -fsSL "$(ICON_URL_BASE)/$(ICON_TTF_FILE)" -o "$(ICON_TTF)"
	curl -fsSL "$(ICON_URL_BASE)/$(ICON_CP_FILE)"  -o "$(ICON_CP)"
	@echo ">>> Icons saved to $(ASSETS_DIR)/"

## Force-refresh icon font assets (re-download even if files already exist).
icons:
	@rm -f "$(ICON_TTF)" "$(ICON_CP)"
	$(MAKE) $(ICON_TTF)

# File rule: generate .ico from appicon.png for Windows PE resource embedding.
# `win` depends on this; ImageMagick (brew install imagemagick) is required.
$(APPICON_ICO): assets/appicon.png
	@command -v magick >/dev/null 2>&1 || \
		(echo "Error: ImageMagick not found. Run: brew install imagemagick" && exit 1)
	magick assets/appicon.png -define icon:auto-resize=256,48,32,16 "$(APPICON_ICO)"
	@echo ">>> Generated: $(APPICON_ICO)"

## Regenerate assets/appicon.ico from assets/appicon.png.
appicon-ico:
	@rm -f "$(APPICON_ICO)"
	$(MAKE) $(APPICON_ICO)

## Validate schema.toml without building the GUI binary.
schema-check:
	@echo ">>> Validating schema  (schema: $(ABS_SCHEMA))"
	cargo run --quiet --bin schema-check -- "$(ABS_SCHEMA)"

## macOS / Linux release binary (current arch, for bundling into parent app).
binary: $(ICON_TTF)
	@echo ">>> Building release binary  (schema: $(ABS_SCHEMA))"
	SETTINGS_SCHEMA=$(ABS_SCHEMA) cargo build --release
	@echo ">>> Output: $(RELEASE_BIN)"

## Windows .exe (cross-compiled from macOS via mingw-w64).
##   Prerequisites: brew install mingw-w64
##                  rustup target add x86_64-pc-windows-gnu
win: $(ICON_TTF) $(APPICON_ICO)
	@echo ">>> Building Windows .exe  (schema: $(ABS_SCHEMA))"
	SETTINGS_SCHEMA=$(ABS_SCHEMA) CARGO_TARGET_DIR="$(WIN_TARGET_DIR)" \
		cargo build --release --target $(WIN_TARGET)
	@mkdir -p "$(WIN_DIR)"
	@cp "$(WIN_TARGET_DIR)/$(WIN_TARGET)/release/settings.exe" "$(WIN_EXE)"
	@echo ">>> Output: $(WIN_EXE)"

## Package the Windows .exe into a distributable zip.
win-zip: win
	@cd "$(DIST)" && zip -j "$(notdir $(WIN_ZIP))" "settings-windows/$(APP_NAME).exe"
	@echo ">>> Package: $(WIN_ZIP)"

## Remove build artefacts.
clean:
	cargo clean
	rm -rf $(DIST) $(WIN_TARGET_DIR)

## Show this help.
help:
	@grep -E '^##' Makefile | sed 's/^## //'
